### ISSUE TITLE
Implement `itk-iku-Cans-Latn-1976` and `bgnpcgn-iku-Cans-Latn-2013`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript#635]
New authority: `itk` => "Inuit Cultural Institute"

Metadata:
itk-iku-Cans-Latn-1976:
```yaml
authority_id: itk
id: 1976
language: iso-639-2:iku
source_script: Cans
destination_script: Latn
name: ICI Standard Orthography
url: https://www.itk.ca/amaujaq/unification-writing-system
creation_date: 1976
```

Metadata:
bgnpcgn-iku-Cans-Latn-2013
(inherits from `itk-iku-Cans-Latn-1976` directly)
```yaml
authority_id: bgnpcgn
id: 2013
language: iso-639-2:isl
source_script: Cans
destination_script: Latn
name: BGN/PCGN Table of Correspondences Syllabics--Roman-script 2013 Agreement
url: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/703402/TABLE_OF_CORRESPONDENCES_FOR_INUKTITUT.pdf
creation_date: 2013
```
